name: Policy Check

on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifest-dir with custom policies
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@v1.2.0
        with:
          file: manifests/goapp.yaml
          policy: policy/latest-tag-check.rego
          token: ${{ secrets.GITHUB_TOKEN }}
